# Generated by Django 5.0.6 on 2024-05-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_arquivo_tipo_artigo_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='conteudo',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
